#:kivy 1.11.0


<AddTextButton>:
    size_hint: None, None
    size: 70, 70
    Button:
        


<MainScreen@Screen>:
    name: "main"

    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Learn it!"

        FloatLayout:
            ScrollView:
                MDLabel:
                    text: "main"

            MDFloatingActionButton:
                icon: "plus"
                md_bg_color: app.theme_cls.primary_color
                pos_hint: {"right": (self.parent.width - 30) / self.parent.width, "y": 30 / self.parent.height}
                width: self.height
                on_release:
                    root.manager.current = "addingtext"


<SettingsScreen@Screen>:
    name: "settings"

    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Настройки"
        
        ScrollView:
            MDList:
                OneLineListItem:
                    text: "Dark theme"
                    MDSwitch:
                        pos_hint: {'center_x': .9, 'center_y': .5}
                        on_active: app.change_theme(*args)


        BoxLayout:
            MDFlatButton:
                text: "settings"


<AddingTextScreen@Screen>:
    name: "addingtext"
    BoxLayout:
        orientation: "vertical"

        MDToolbar:
            title: "Learn it!"
            #save text
            MDIconButton:
                user_font_size: "45sp"
                icon: 'check'
                pos_hint: {"center_x": 0.9, "center_y": 0.5}

        MDTextField:
            hint_text: "Enter the title"
            mode: "rectangle"
            icon_right_color: app.theme_cls.primary_color

        MDTextField:
            hint_text: "Enter the text"
            mode: "rectangle"
            multiline: True
            size_hint: 1, 1
            icon_right_color: app.theme_cls.primary_color
        

<NavigationDrawerLogo@Image>:
    size_hint: None, None
    width: self.parent.width
    height: self.parent.width / self.image_ratio
    source: "res/book.jpg"


NavigationLayout:
    ScreenManager:
        id: screen_manager

        MainScreen:
        SettingsScreen:
        AddingTextScreen:

    MDNavigationDrawer:
        id: nav_drawer

        BoxLayout:
            orientation: "vertical"

            NavigationDrawerLogo:

            MDList:
                OneLineListItem:
                    text: "Главное меню"
                    on_release:
                        nav_drawer.set_state("close")
                        screen_manager.current = "main"

                OneLineListItem:
                    text: "Настройки"
                    on_release:
                        nav_drawer.set_state("close")
                        screen_manager.current = "settings"

            # just for keep all at the top
            BoxLayout: