#:kivy 1.11.0

#:import Window kivy.core.window.Window
#:import IconLeftWidget kivymd.uix.list.IconLeftWidget
#:import images_path kivymd.images_path

<LearningScreen>:

    Screen:
        canvas:
            # name of app
            Color: 
                rgba: root.name_of_app_color
            Rectangle:
                pos: 0, self.height - 0.08 * self.height
                size: root.width, 0.08 * self.height

            # menu
            Color: 
                rgba: root.menu_color
            Rectangle:
                pos: 0, 0
                size: root.width, 0.1 * self.height
            # background
            Color: 
                rgba: root.b_ground_color
            Rectangle:
                pos: 0, 0
                size: root.width, self.height

        # name of app
        Label:
            color: (0, 0, 0, 1)
            font_size: 25
            text: "LearnIT"
            pos_hint: {"center_x": 0.2, "center_y": 0.965}

        # search field
        BoxLayout:
            size_hint: None, None
            height: self.minimum_height
            width: root.width * 3 / 4
            pos: 10, root.height - 0.18 * root.height

            MDIconButton:
                icon: 'magnify'

            MDTextField:
                id: search_field
                color_mode: 'custom'
                hint_text: 'Search text'
                line_color_focus: 0, 0, 0, 1

        # menu buttons
        MDIconButton:
            user_font_size: "45sp"
            icon: "book-open-page-variant"
            pos_hint: {"center_x": 0.2, "center_y": 0.055}
        MDIconButton:
            user_font_size: "45sp"
            icon: "note-text"
            pos_hint: {"center_x": 0.5, "center_y": 0.055}
            on_press:
                root.manager.current = 'Listoftexts'
        MDIconButton:
            user_font_size: "45sp"
            icon: 'settings'
            pos_hint: {"center_x": 0.8, "center_y": 0.055}
            on_press:
                root.manager.current = 'Settings'
        
        # microphone
        MDIconButton:
            user_font_size: "45sp"
            icon: 'microphone'
            pos_hint: {"center_x": 0.8, "center_y": 0.16}

<ListoftextsScreen>:

    Screen:
        BoxLayout:
            orientation: 'horizontal'
            canvas:
                # name of app
                Color: 
                    rgba: root.name_of_app_color
                Rectangle:
                    pos: 0, self.height - 0.08 * self.height
                    size: root.width, 0.08 * self.height

                # menu
                Color: 
                    rgba: root.menu_color
                Rectangle:
                    pos: 0, 0
                    size: root.width, 0.1 * self.height

                # background
                Color: 
                    rgba: root.b_ground_color
                Rectangle:
                    pos: 0, 0
                    size: root.width, self.height

        # name of app
        Label:
            color: (0, 0, 0, 1)
            font_size: 25
            text: "LearnIT"
            pos_hint: {"center_x": 0.2, "center_y": 0.965}

        # menu buttons
        MDIconButton:
            user_font_size: "45sp"
            icon: "book-open-page-variant"
            pos_hint: {"center_x": 0.2, "center_y": 0.055}
            on_press:
                root.manager.current = 'Learning'
        MDIconButton:
            user_font_size: "45sp"
            icon: "note-text"
            pos_hint: {"center_x": 0.5, "center_y": 0.055}
        MDIconButton:
            user_font_size: "45sp"
            icon: 'settings'
            pos_hint: {"center_x": 0.8, "center_y": 0.055}
            on_press:
                root.manager.current = 'Settings'

        # adding the text
        MDIconButton:
            user_font_size: "45sp"
            icon: 'plus'
            pos_hint: {"center_x": 0.9, "center_y": 0.965}
            on_press:
                root.manager.current = 'AddText'


<SettingsScreen>:
    Screen:
        BoxLayout:
            orientation: 'horizontal'
            canvas:
                # name of app
                Color: 
                    rgba: root.name_of_app_color
                Rectangle:
                    pos: 0, self.height - 0.08 * self.height
                    size: root.width, 0.08 * self.height

                # menu
                Color: 
                    rgba: root.menu_color
                Rectangle:
                    pos: 0, 0
                    size: root.width, 0.1 * self.height

                # background
                Color: 
                    rgba: root.b_ground_color
                Rectangle:
                    pos: 0, 0
                    size: root.width, self.height

        # name of app
        Label:
            color: (0, 0, 0, 1)
            font_size: 25
            text: "LearnIT"
            pos_hint: {"center_x": 0.2, "center_y": 0.965}

        # menu buttons
        MDIconButton:
            user_font_size: "45sp"
            icon: "book-open-page-variant"
            pos_hint: {"center_x": 0.2, "center_y": 0.055}
            on_press:
                root.manager.current = 'Learning'
        MDIconButton:
            user_font_size: "45sp"
            icon: "note-text"
            pos_hint: {"center_x": 0.5, "center_y": 0.055}
            on_press:
                root.manager.current = 'Listoftexts'
        MDIconButton:
            user_font_size: "45sp"
            icon: 'settings'
            pos_hint: {"center_x": 0.8, "center_y": 0.055}
            

<AddingTextScreen>:
    Screen:
        canvas:
            # name of app
            Color: 
                rgba: root.name_of_app_color
            Rectangle:
                pos: 0, self.height - 0.08 * self.height
                size: root.width, 0.08 * self.height

            # background
            Color: 
                rgba: root.b_ground_color
            Rectangle:
                pos: 0, 0
                size: root.width, self.height

        # name of app
        Label:
            color: (0, 0, 0, 1)
            font_size: 25
            text: "LearnIT"
            pos_hint: {"center_x": 0.3, "center_y": 0.965}

        # go back
        MDIconButton:
            user_font_size: "45sp"
            icon: 'arrow-left-drop-circle-outline'
            pos_hint: {"center_x": 0.1, "center_y": 0.965}
            on_press:
                root.manager.current = 'Listoftexts'

        #save text
        MDIconButton:
            user_font_size: "45sp"
            icon: 'check'
            pos_hint: {"center_x": 0.9, "center_y": 0.965}
            on_press:
                root.manager.current = 'Listoftexts'

        # text input
        BoxLayout:
            size_hint: None, None
            height: root.height - 0.08 * self.height
            width: root.width
            pos: 0, 0

            TextInput:
                size_hint: None, None
                id: add_the_text
                multiline: True
                height: root.height - 0.08 * root.height
                width: root.width
                hint_text: 'Add the text'
                pos: 0, 0
                line_color_focus: 0, 0, 0, 1
                focus: True
